import mammoth from 'mammoth'
import { PDFParse } from 'pdf-parse'
import { GoogleGenAI, Type } from '@google/genai'
import jobRoles from '../data/jobRoles.js'

const model = () => process.env.GEMINI_MODEL || 'gemini-3.6-flash'
const meaningful = (value) => typeof value === 'string' && value.trim() && !/^\.+$/.test(value.trim())
const stringArray = (value) => (Array.isArray(value) ? value : typeof value === 'string' ? value.split(/[,;\n]/) : []).map((item) => typeof item === 'string' ? item.trim() : item?.name || item?.value || '').filter(meaningful)
const objectArray = (value) => Array.isArray(value) ? value.filter((item) => item && typeof item === 'object') : []

export const isSupportedResume = (file) => /\.(pdf|docx)$/i.test(file.originalname)
export async function extractResumeText(file) { let text = ''; if (/\.pdf$/i.test(file.originalname)) { const parser = new PDFParse({ data: file.buffer }); text = (await parser.getText()).text; await parser.destroy() } else if (/\.docx$/i.test(file.originalname)) text = (await mammoth.extractRawText({ buffer: file.buffer })).value; text = text.replace(/\r/g, '').replace(/\n{3,}/g, '\n\n').replace(/[ \t]{2,}/g, ' ').trim(); if (text.length < 80) throw Object.assign(new Error('We could not extract readable text. Please upload a text-based PDF or DOCX resume.'), { status: 422 }); return text }
export async function parseResume(text) { if (!process.env.GEMINI_API_KEY) throw Object.assign(new Error('Resume analysis is not configured yet. Please add GEMINI_API_KEY to backend/.env.'), { status: 503 }); const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY }); const response = await ai.models.generateContent({ model: model(), contents: `Extract only facts from this resume. Never invent skills or experience. Use empty arrays for absent lists; never use punctuation placeholders.\n${text}`, config: { responseMimeType: 'application/json', responseSchema: { type: Type.OBJECT, properties: { name: { type: Type.STRING }, email: { type: Type.STRING }, professionalSummary: { type: Type.STRING }, skills: { type: Type.ARRAY, items: { type: Type.STRING } }, education: { type: Type.ARRAY, items: { type: Type.OBJECT } }, experience: { type: Type.ARRAY, items: { type: Type.OBJECT } }, projects: { type: Type.ARRAY, items: { type: Type.OBJECT } }, certifications: { type: Type.ARRAY, items: { type: Type.STRING } }, achievements: { type: Type.ARRAY, items: { type: Type.STRING } }, languages: { type: Type.ARRAY, items: { type: Type.STRING } }, resumeSectionsPresent: { type: Type.ARRAY, items: { type: Type.STRING } } } } } }); return JSON.parse(response.text) }
export const normalizeResume = (profile = {}) => ({ name: meaningful(profile.name) ? profile.name.trim() : '', email: meaningful(profile.email) ? profile.email.trim() : '', professionalSummary: meaningful(profile.professionalSummary) ? profile.professionalSummary.trim() : '', summary: meaningful(profile.professionalSummary) ? profile.professionalSummary.trim() : '', skills: stringArray(profile.skills), education: objectArray(profile.education), experience: objectArray(profile.experience), projects: objectArray(profile.projects), certifications: stringArray(profile.certifications), achievements: stringArray(profile.achievements), languages: stringArray(profile.languages), resumeSectionsPresent: stringArray(profile.resumeSectionsPresent), resumeSectionsMissing: stringArray(profile.resumeSectionsMissing) })
export const deterministicMatches = (resume) => jobRoles.map((role) => { const required = role.requiredSkills || role.coreSkills || []; const matched = required.filter((skill) => resume.skills.some((value) => value.toLowerCase().includes(skill.toLowerCase()))); return { role, matched, score: Math.round((matched.length / Math.max(required.length, 1)) * 70) } }).sort((a, b) => b.score - a.score).slice(0, 4)
export async function contextualAnalysis(resume, matches) { const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY }); const response = await ai.models.generateContent({ model: model(), contents: `Using only the profile ${JSON.stringify(resume)} and roles ${JSON.stringify(matches.map((m) => m.role.title))}, return factual JSON. Never invent skills. Use [] when no item is useful. Never emit '.', '...', Markdown, or placeholders.`, config: { responseMimeType: 'application/json', responseSchema: { type: Type.OBJECT, properties: { semanticScores: { type: Type.ARRAY, items: { type: Type.NUMBER } }, strengths: { type: Type.ARRAY, items: { type: Type.STRING } }, missingSkills: { type: Type.ARRAY, items: { type: Type.OBJECT, properties: { skill: { type: Type.STRING }, importance: { type: Type.STRING }, reason: { type: Type.STRING } } } }, missingSections: { type: Type.ARRAY, items: { type: Type.OBJECT, properties: { section: { type: Type.STRING }, importance: { type: Type.STRING }, reason: { type: Type.STRING } } } }, improvementSuggestions: { type: Type.ARRAY, items: { type: Type.OBJECT, properties: { category: { type: Type.STRING }, suggestion: { type: Type.STRING } } } }, overallSummary: { type: Type.STRING } } } } }); return normalizeContextualAnalysis(JSON.parse(response.text)) }
export function normalizeContextualAnalysis(value = {}) { const named = (items, key) => objectArray(items).map((item) => ({ [key]: meaningful(item[key]) ? item[key].trim() : '', importance: meaningful(item.importance) ? item.importance.trim().toLowerCase() : 'medium', reason: meaningful(item.reason) ? item.reason.trim() : '' })).filter((item) => item[key]); return { semanticScores: (Array.isArray(value.semanticScores) ? value.semanticScores : []).map(Number).filter(Number.isFinite).map((score) => Math.max(0, Math.min(100, score))), strengths: stringArray(value.strengths), missingSkills: named(value.missingSkills, 'skill'), missingSections: named(value.missingSections, 'section'), improvementSuggestions: objectArray(value.improvementSuggestions).map((item) => ({ category: meaningful(item.category) ? item.category.trim() : '', suggestion: meaningful(item.suggestion) ? item.suggestion.trim() : '' })).filter((item) => item.category && item.suggestion), overallSummary: meaningful(value.overallSummary) ? value.overallSummary.trim() : '' } }
